const instrumentation = require('./instrumentation.js');
const works = [
    // piano trios
    {
        title: 'Piano Trio #1',
        key: 'Eb',
        mode: 'Major',
        genre: 'Piano Trio',
        opus: 1,
        instrumentation: instrumentation.pianoTrio,
    },
    {
        title: 'Piano Trio #2',
        key: 'G',
        mode: 'Major',
        genre: 'Piano Trio',
        opus: 1,
        instrumentation: instrumentation.pianoTrio,
    },
    {
        title: 'Piano Trio #3',
        key: 'C',
        mode: 'Minor',
        genre: 'Piano Trio',
        opus: 1,
        instrumentation: instrumentation.pianoTrio,
    },
    {
        title: 'Piano Trio #4',
        key: 'Bb',
        mode: 'Major',
        genre: 'Piano Trio',
        opus: 11,
        instrumentation: instrumentation.pianoTrio,
    },
    {
        title: 'Variations on an Original Theme',
        key: 'Eb',
        mode: 'Major',
        genre: 'Piano Trio',
        opus: 44,
        instrumentation: instrumentation.pianoTrio,
    },
    {
        title: 'Piano Trio',
        key: 'Eb',
        mode: 'Major',
        genre: 'Piano Trio',
        opus: 63,
        instrumentation: instrumentation.pianoTrio,
    },
    {
        title: 'Piano Trio #5',
        key: 'D',
        mode: 'Major',
        genre: 'Piano Trio',
        opus: 70,
        instrumentation: instrumentation.pianoTrio,
    },
    {
        title: 'Piano Trio #6',
        key: 'Eb',
        mode: 'Major',
        genre: 'Piano Trio',
        opus: 70,
        instrumentation: instrumentation.pianoTrio,
    },
    {
        title: 'Piano Trio #7',
        key: 'Bb',
        mode: 'Major',
        genre: 'Piano Trio',
        opus: 72,
        instrumentation: instrumentation.pianoTrio,
    },
    {
        title: 'Kakadu Variations',
        key: 'G',
        mode: 'Minor',
        genre: 'Piano Trio',
        opus: 121,
        instrumentation: instrumentation.pianoTrio,
    },
    // string trios
    {
        title: 'String Trio #1 ',
        key: 'Eb',
        mode: 'Major',
        genre: 'String Trio',
        opus: 2,
        instrumentation: instrumentation.stringTrio,
    },
    {
        title: 'String Trio #2 ',
        key: 'D',
        mode: 'Major',
        genre: 'String Trio',
        opus: 8,
        instrumentation: instrumentation.stringTrio,
    },
    {
        title: 'String Trio #3 ',
        key: 'G',
        mode: 'Major',
        genre: 'String Trio',
        opus: 9,
        instrumentation: instrumentation.stringTrio,
    },
    {
        title: 'String Trio #4 ',
        key: 'D',
        mode: 'Major',
        genre: 'String Trio',
        opus: 9,
        instrumentation: instrumentation.stringTrio,
    },
    {
        title: 'String Trio #5 ',
        key: 'C',
        mode: 'Minor',
        genre: 'String Trio',
        opus: 9,
        instrumentation: instrumentation.stringTrio,
    },
    // string quartets
    {
        title: 'String Quartet #1',
        key: 'F',
        mode: 'Minor',
        genre: 'String Quartet',
        opus: 18,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #2',
        key: 'G',
        mode: 'Major',
        genre: 'String Quartet',
        opus: 18,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #3',
        key: 'D',
        mode: 'Major',
        genre: 'String Quartet',
        opus: 18,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #4',
        key: 'C',
        mode: 'Minor',
        genre: 'String Quartet',
        opus: 18,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #5',
        key: 'A',
        mode: 'Major',
        genre: 'String Quartet',
        opus: 18,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #6',
        key: 'Bb',
        mode: 'Major',
        genre: 'String Quartet',
        opus: 18,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #7',
        key: 'F',
        mode: 'Major',
        genre: 'String Quartet',
        opus: 59,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #8',
        key: 'E',
        mode: 'Minor',
        genre: 'String Quartet',
        opus: 59,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #9',
        key: 'C',
        mode: 'Major',
        genre: 'String Quartet',
        opus: 59,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #10',
        key: 'Eb',
        mode: 'Major',
        genre: 'String Quartet',
        opus: 74,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #11',
        key: 'F',
        mode: 'Minor',
        genre: 'String Quartet',
        opus: 95,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #12',
        key: 'Eb',
        mode: 'Major',
        genre: 'String Quartet',
        opus: 127,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #13',
        key: 'Bb',
        mode: 'Major',
        genre: 'String Quartet',
        opus: 130,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #14',
        key: 'Cs',
        mode: 'Minor',
        genre: 'String Quartet',
        opus: 131,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #15',
        key: 'A',
        mode: 'Minor',
        genre: 'String Quartet',
        opus: 132,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'Grosse Fugue',
        key: 'Bb',
        mode: 'Major',
        genre: 'String Quartet',
        opus: 133,
        instrumentation: instrumentation.stringQuartet,
    },
    {
        title: 'String Quartet #16',
        key: 'F',
        mode: 'Major',
        genre: 'String Quartet',
        opus: 135,
        instrumentation: instrumentation.stringQuartet,
    },
    // string quintets
    {
        title: 'String Quintet',
        key: 'Eb',
        mode: 'Major',
        genre: 'String Quintet',
        opus: 4,
        instrumentation: instrumentation.stringQuintet,
    },
    {
        title: 'String Quintet',
        key: 'C',
        mode: 'Major',
        genre: 'String Quintet',
        opus: 29,
        instrumentation: instrumentation.stringQuintet,
    },
    {
        title: 'String Quintet',
        key: 'C',
        mode: 'Minor',
        genre: 'String Quintet',
        opus: 104,
        instrumentation: instrumentation.stringQuintet,
    },
    {
        title: 'Fugue for String Quintet',
        key: 'D',
        mode: 'Major',
        genre: 'String Quintet',
        opus: 137,
        instrumentation: instrumentation.stringQuintet,
    },
    // chamber with winds
    {
        title: 'Quintet for Piano and Winds',
        key: 'Eb',
        mode: 'Major',
        genre: 'Piano and Wind Quintet',
        opus: 16,
        instrumentation: [
            'Piano',
            'Oboe',
            'Clarinet',
            'Horn',
            'Bassoon',
        ],
    },
    {
        title: 'Septet',
        key: 'Eb',
        mode: 'Major',
        genre: 'Wind and String Septet',
        opus: 20,
        instrumentation: [
            'Clarinet',
            'Horn',
            'Bassoon',
            'Violin',
            'Viola',
            'Cello',
            'Bass',
        ],
    },
    {
        title: 'Serenade',
        key: 'D',
        mode: 'Major',
        genre: 'Serenade',
        opus: 25,
        instrumentation: [
            'Flute',
            'Violin',
            'Viola',
        ],
    },
    {
        title: 'Trio',
        key: 'Eb',
        mode: 'Major',
        genre: 'Piano Trio',
        opus: 38,
        instrumentation: [
            'Clarinet',
            'Cello',
            'Piano',
        ],
    },
    {
        title: 'Sextet',
        key: 'Eb',
        mode: 'Major',
        genre: 'Wind Sextet',
        opus: 71,
        instrumentation: [
            'Clarinet',
            'Horn',
            'Bassoon',
        ],
    },
    {
        title: 'Sextet',
        key: 'Eb',
        mode: 'Major',
        genre: 'Wind Sextet',
        opus: 71,
        instrumentation: [
            'Clarinet',
            'Horn',
            'Bassoon',
        ],
    },
    {
        title: 'Trio',
        key: 'C',
        mode: 'Major',
        genre: 'Wind Trio',
        opus: 87,
        instrumentation: [
            'Oboe',
            'English Horn',
        ],
    },
    {
        title: 'Wind Octet',
        key: 'Eb',
        mode: 'Major',
        genre: 'Wind Octet',
        opus: 103,
        instrumentation: [
            'Oboe',
            'Clarinet',
            'Horn',
            'Bassoon',
        ],
    },
    {
        title: 'Six Variations',
        key: 'Various',
        mode: 'Various',
        genre: 'Variations',
        opus: 105,
        instrumentation: [
            'Flute',
            'Piano',
        ],
    },
    {
        title: 'Ten Variations',
        key: 'Various',
        mode: 'Various',
        genre: 'Variations',
        opus: 107,
        instrumentation: [
            'Flute',
            'Piano',
        ],
    },

    // piano sonatas
    {
        title: 'Piano Sonata #1',
        key: 'F',
        mode: 'Minor',
        genre: 'Piano Sonata',
        opus: 2,
        instrumentation: instrumentation.piano,
    },
];

module.exports = works;
